apps += NativeApps::App
app_headers += apps/native_apps/app.h
apps_src += apps/native_apps/app.cpp apps/native_apps/menu.cpp
i18n_files += apps/native_apps/base.universal.i18n

$(eval $(call depends_on_image,apps/native_apps/menu.cpp,apps/external/external_icon.png))
