FROM debian:bookworm-slim

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      binutils-arm-none-eabi \
      build-essential \
      ca-certificates \
      gcc-arm-none-eabi \
      git \
      libfreetype-dev \
      libpng-dev \
      make \
      pkg-config \
      python3 \
 && rm -rf /var/lib/apt/lists/*

ENV LC_ALL=C.UTF-8
