FROM debian:bookworm-slim

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      build-essential \
      ca-certificates \
      libfreetype-dev \
      libjpeg-dev \
      libpng-dev \
      libxtst-dev \
      pkg-config \
      python3 \
 && rm -rf /var/lib/apt/lists/*
