#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate the GPL-2.0-or-later U-Boot research patch table, without HP files."""
from pathlib import Path
import argparse
from prime_hp_confinement import patches


def generate():
    lines = ['/* SPDX-License-Identifier: GPL-2.0-or-later */',
             '/* Generated by scripts/generate_prime_hp_confinement.py. Emulator research only. */',
             'struct hp_patch { unsigned long address; unsigned length; unsigned char before[128], after[128]; };']
    def bytes_c(data):return '{'+','.join(f'0x{x:02x}' for x in data)+'}'
    for name,label in [('HPPrime.img','os'),('bootloader.img','updater')]:
        lines.append(f'static const struct hp_patch hp_patches_{label}[] = {{')
        for p in patches(name):
            assert len(p.expected)<=128
            lines.append(f'    /* {p.purpose} */')
            lines.append(f'    {{0x{p.address:08x}UL, {len(p.expected)}, {bytes_c(p.expected)}, {bytes_c(p.replacement)}}},')
        lines.append('};')
    return '\n'.join(lines)+'\n'


if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('output',type=Path)
    p.parse_args().output.write_text(generate())
