#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate the boot menu's small antialiased ASCII atlas from bundled OFL Roboto."""
import argparse
import hashlib
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
ROOT = Path(__file__).resolve().parents[1]
FONT = ROOT / 'native/prime_g2/bootmenu/fonts/Roboto.ttf'
SHA = 'd7598e12c5dbef095ff8272cfc55da0250bd07fbdecbac8a530b9b277872a134'
def generate(path):
    if hashlib.sha256(FONT.read_bytes()).hexdigest() != SHA:
        raise ValueError('unexpected Roboto input')
    lines = ['/* Generated by scripts/generate_bootmenu_font.py. Roboto: SIL OFL 1.1;',
             ' * see fonts/OFL.txt. The generator is GPL-3.0-or-later. */',
             'struct lf_glyph { unsigned short offset; unsigned char width, advance; };']
    for size in (12, 16, 28):
        font = ImageFont.truetype(str(FONT), size)
        pixels = bytearray(); glyphs = []
        for code in range(32,127):
            char = chr(code); advance = round(font.getlength(char))
            width = max(1, advance + 2)
            im = Image.new('L',(width,size+6))
            ImageDraw.Draw(im).text((0,0),char,font=font,fill=255)
            # Pack two 4-bit alpha pixels per byte, pad rows to even widths.
            width += width % 2
            padded = Image.new('L',(width,size+6)); padded.paste(im,(0,0))
            data = list(padded.tobytes()); glyphs.append((len(pixels),width,advance))
            pixels.extend(((data[i]+8)//17 << 4) | ((data[i+1]+8)//17) for i in range(0,len(data),2))
        lines += [f'static const struct lf_glyph lf_glyph_{size}[] = {{',
                  ',\n'.join('{%d,%d,%d}' % g for g in glyphs), '};',
                  f'static const unsigned char lf_font_{size}[] = {{',
                  ',\n'.join(','.join(str(x) for x in pixels[i:i+32]) for i in range(0,len(pixels),32)), '};']
    path.write_text('\n'.join(lines)+'\n')
if __name__ == '__main__':
    ap=argparse.ArgumentParser(description=__doc__);ap.add_argument('output',type=Path)
    generate(ap.parse_args().output)
