#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Opt-in native firmware contract for the Phase 5 emulator candidate."""
import argparse
from pathlib import Path
from prime_dual_boot_contract import layout_digest


def prepare(tree):
    target=Path(tree)/'ion/src/prime_g2/dual_boot_build.h'
    if not target.is_file(): raise ValueError('missing dual-boot firmware source overlay')
    target.write_text('// SPDX-License-Identifier: CC-BY-NC-SA-4.0\n'
                      '// Generated by prepare_prime_dual_firmware.py.\n'
                      '#define LEFONY_DUAL_BOOT_CANDIDATE 1\n'
                      'static constexpr unsigned char LefonyDualLayoutSHA[32] = {'+
                      ','.join(hex(x) for x in layout_digest())+'};\n')


if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('tree',type=Path)
    prepare(p.parse_args().tree)
