#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Exact V15751 wake-to-menu hooks, separate from NAND confinement policy.

Embedded ARM code and generated U-Boot fragments are GPL-2.0-or-later.
HP's save/suspend implementation is retained. Full power-off requests the menu
on the next cold boot; a completed suspend wake resets through NAND. Nothing
here edits vendor files in place or changes filesystem/write boundaries.
"""
from prime_hp_confinement import Patch, assemble, apply_patches
from analyze_hp_prime_compatibility import verify_input, require

PROFILE = 'hp-v15751-wake-menu-v1'
REQUEST = 0x314d464c  # LFM1, one-use SNVS LPGPR request
HELPER = 0x80000d00
POWER_OFF = 0x80000e00
WAKE = 0x80000e80


def patches():
    # Same single-word SNVS mailbox and PGD initialization used by native
    # recovery. Bounded reads cover the asynchronous 32 kHz write domain.
    helper = assemble(f'''
        push {{r1,r2,r3,lr}}
        ldr r1, =0x020cc000
        ldr r2, [r1]
        tst r2, #32
        bne failed
        ldr r2, [r1, #0x34]
        tst r2, #32
        bne failed
        ldr r2, [r1, #0x68]
        ldr r3, =0x4b4f464c
        cmp r2, r3
        beq failed
        ldr r2, [r1, #0x4c]
        tst r2, #8
        beq request
        ldr r2, =0x41736166
        str r2, [r1, #0x64]
        dsb sy
        movs r2, #8
        str r2, [r1, #0x4c]
        movw r3, #65535
    clear_wait:
        ldr r2, [r1, #0x4c]
        tst r2, #8
        beq request
        subs r3, #1
        bne clear_wait
        b failed
    request:
        ldr r2, =0x{REQUEST:x}
        str r2, [r1, #0x68]
        dsb sy
        movw r3, #65535
    request_wait:
        ldr r0, [r1, #0x68]
        cmp r0, r2
        beq success
        subs r3, #1
        bne request_wait
    failed:
        movs r0, #0
        pop {{r1,r2,r3,pc}}
    success:
        movs r0, #1
        pop {{r1,r2,r3,pc}}
        .ltorg
    ''', HELPER)
    require(len(helper) <= 0x100, 'wake helper exceeds cave')
    off = assemble(f'''
        push {{r3,lr}}
        bl 0x{HELPER:x}
        pop {{r3,lr}}
        ldr r0, =0x020cc038
        ldr r1, [r0]
        b.w 0x803a4c22
        .ltorg
    ''', POWER_OFF)
    wake = assemble(f'''
        push {{r4,lr}}
        bl 0x802b370e
        bl 0x{HELPER:x}
        cmp r0, #0
        beq resume
        cpsid if
        /* i.MX6UL/ULL CCGR3 CG8: WDOG1 clock, pinned U-Boot crm_regs.h. */
        ldr r1, =0x020c4074
        ldr r2, [r1]
        orr r2, r2, #0x30000
        str r2, [r1]
        dsb sy
        ldr r1, =0x020bc000
        movs r0, #0
        strh r0, [r1]
        strh r0, [r1]
        strh r0, [r1]
        dsb sy
    reset_wait:
        wfi
        b reset_wait
    resume:
        pop {{r4,pc}}
        .ltorg
    ''', WAKE)
    require(len(off) <= 0x80 and len(wake) <= 0x80, 'wake trampoline exceeds cave')
    result = []
    for address, code, purpose in ((HELPER, helper, 'retained-menu-request'),
                                   (POWER_OFF, off, 'menu-on-cold-wake'),
                                   (WAKE, wake, 'menu-after-suspend-wake')):
        for at in range(0, len(code), 64):
            part = code[at:at+64]
            result.append(Patch(address+at, b'\xff'*len(part), part, purpose))
    result.extend((
        Patch(0x803a4c1e, bytes.fromhex('2a480168'),
              assemble(f'b.w 0x{POWER_OFF:x}', 0x803a4c1e), 'power-off-entry'),
        Patch(0x8039df28, bytes.fromhex('15f7f1fb'),
              assemble(f'bl 0x{WAKE:x}', 0x8039df28), 'completed-wake-call'),
    ))
    return tuple(result)


def patch_image(data):
    verify_input('HPPrime.img', data)
    return apply_patches(data, patches())


def generate():
    def array(data):
        return '{' + ','.join(f'0x{x:02x}' for x in data) + '}'
    lines = ['/* SPDX-License-Identifier: GPL-2.0-or-later */',
             '/* Generated by prime_hp_wake_menu.py; exact V15751 only. */',
             'static const struct hp_patch hp_wake_patches[] = {']
    for patch in patches():
        lines += [f'    /* {patch.purpose} */',
                  f'    {{0x{patch.address:08x}UL, {len(patch.expected)}, '
                  f'{array(patch.expected)}, {array(patch.replacement)}}},']
    return '\n'.join(lines + ['};', ''])


if __name__ == '__main__':
    import argparse
    from pathlib import Path
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('output', type=Path)
    parser.parse_args().output.write_text(generate())
